---
kind: KafkaConnector
apiVersion: kafka.strimzi.io/v1alpha1
metadata:
  name: mongodb-sink
  labels:
    # must match connect cluster name
    strimzi.io/cluster: my-cluster-connect
spec:
  tasksMax: 1
  class: org.apache.camel.kafkaconnector.mongodb.CamelMongodbSinkConnector
  config:
    topics: greetings
    # due to current limitation of CKC 0.5.0, need to hardcode the values
    #camel.beans.mongo: "${file:/opt/kafka/external-configuration/mongodb-connection-props/mongodb-connection.properties:connectionBeanDef}"
    camel.beans.mongo: '#class:com.mongodb.client.MongoClients#create("mongodb://mongoadmin:password@mongodb.mongodb:27017")'
    camel.sink.path.connectionBean: "mongo"
    camel.sink.endpoint.database: "demos"
    camel.sink.endpoint.collection: "greetings"
    camel.sink.endpoint.operation: "save"
    key.converter: org.apache.kafka.connect.storage.StringConverter
    value.converter: org.apache.kafka.connect.json.JsonConverter
    value.converter.schemas.enable: "false"